image: python:3.8

test:
  stage: test
  only:
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-test/
  cache:
    paths:
      - .cache/pip
      - venv/
  script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate

    - python setup.py install
    - pytest
