image: python:3.8

before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - python setup.py install

test:
  stage: test
  only:
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-test/
  cache:
    paths:
      - .cache/pip
      - venv/
  script:
    - pytest

pages:
  stage: deploy
  script:
    - pip install mkdocs mkdocs-material mkdocstrings pymdown-extensions
    - mkdocs build --verbose
  artifacts:
    paths:
      - site
  only:
    - master
