image: python:3.8

before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - make install

test:
  stage: test
  only:
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-test/
  cache:
    paths:
      - .cache/pip
      - venv/
  script:
    - pytest

pages:
  stage: deploy
  script:
    - pip install -r docs/requirements.txt
    - make docs-install
  artifacts:
    paths:
      - public
  only:
    - master
