site_name: TaskChain
site_description: Documentation and examples for TaskChain
site_url: https://flowerchecker.gitlab.io/taskchain/
repo_url: https://gitlab.com/flowerchecker/taskchain
code_url: https://gitlab.com/flowerchecker/taskchain/-/tree/master

theme:
  name: material

nav:
  - Introduction: index.md
  - Tasks: tasks.md
  - Configs: configs.md
  - Chains: chains.md
  - Example:  example.md
  - Utils: utils.md
  - Code Reference:
      - Task: code/task.md
      - Parameter: code/parameter.md
      - Config: code/config.md
      - Chain: code/chain.md
      - Utils: code/utils.md


markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences

plugins:
  - search
  - macros
  - mkdocstrings:
      watch:
        - src/taskchain
