site_name: TaskChain
site_description: Documentation and examples for TaskChain
site_url: https://flowerchecker.gitlab.io/taskchain/
base_url: /taskchain
repo_url: https://github.com/thran/taskchain
code_url: https://github.com/thran/taskchain/tree/master

theme:
  name: material

nav:
  - Introduction: index.md
  - Tasks: tasks.md
  - Configs: configs.md
  - Chains: chains.md
  - Example project:  example.md
  - Utils: utils.md
  - Testing: testing.md
  - CheatSheet: cheatsheet.md
  - Code Reference:
      - Task: code/task.md
      - Parameter: code/parameter.md
      - Config: code/config.md
      - Chain: code/chain.md
      - Utils: code/utils.md
      - Testing: code/testing.md


markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences

plugins:
  - search
  - macros
  - mkdocstrings:
      watch:
        - src/taskchain
      handlers:
        python:
          rendering:
            show_root_toc_entry: false
            members_order: source

extra_css: [extra.css]
