site_name: TaskChain
site_description: Documentation and examples for TaskChain
site_url: https://flowerchecker.gitlab.io/taskchain/
repo_url: https://gitlab.com/flowerchecker/taskchain

theme:
  name: material

nav:
  - Overview: index.md
  - Installation: install.md
  - Usage: usage.md
  - Code Reference:
      - Task: code/task.md
      - Chain: code/chain.md
      - Config: code/config.md
      - Parameters: code/parameters.md
      - Utils: code/utils.md


markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      watch:
        - src/taskchain
